name: gradely2
description: Your grades on every device.

# The following line prevents the package from being accidentally published to pub.dev using `pub publish`. 
publish_to: 'none'

version: 1.0.1+3
#Latest builds:
#ios: 1.0.1+3
#MacOS  1.0.0+5
#android: 3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #custom dependencies
  msix: ^2.1.3
  cupertino_icons: ^1.0.2
  appwrite: ^0.7.0
  flutter_slidable: ^0.6.0
  modal_bottom_sheet: ^2.0.0
  flutter_launcher_icons:
  introduction_screen: ^2.1.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  url_launcher:
  mailer: ^5.0.1 
  flutter_icons:
  shared_preferences: ^2.0.6
  emoji_chooser:
  syncfusion_flutter_charts: ^19.1.66+1
  flutter_inapp_purchase: ^5.0.2
  flutter_spinkit: ^5.0.0
  another_flushbar: ^1.10.24
  flutter_svg: ^0.22.0
  package_info_plus: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to the application
  assets:
    - assets/
    - assets/images/light/
    - assets/images/dark/
    - assets/images/
    - assets/translations/


#package to create a msix for windows
#1. flutter build windows
#2. flutter pub run msix:create
msix_config:
  store: true
  display_name: Gradely 2
  publisher_display_name: Elias Schneider
  identity_name: 58500EliasSchneider.Gradely2
  msix_version: 1.0.1.0
  publisher: CN=26AFB924-E2D8-4326-B33D-B268D9E4FB49
  architecture: x64
  capabilities: 'internetClient'
  logo_path: assets\images\gradely2Icon.png
  start_menu_icon_path: assets\images\gradely2Icon.png
  tile_icon_path: assets\images\gradely2Icon.png
  icons_background_color: transparent

#this package generates the app icons for android & ios
#Run this package with: flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/gradely2Icon.png"
  ios: true
  android: true